### ISSUE TITLE
[Bug Report]no tunnel started with system

### ISSUE THREAD

**Issue by stydxm** [hdu-dn11/wg-quick-op#4]
I've follow the steps in readme to install it but it does not function properly after upgrading to v0.1.1. It does work in previous versions but does not in the new one even if I reinstalled the whole system.

my `/etc/wg-quick-op.yml`
```
# up with system, be careful about routing table
enabled:
  - mantle
  - luwyi
  - jbnrz
  - potat0
  - daidr
  - syx
  - iraze
  - asakirain
  - elaina
  - ljcbaby
  - lay
  - gaga

# resolve hostname every interval
ddns:
  # check every interval
  interval: 60
  # when last handshake time is max-last-handshake before now, update interface
  max_last_handshake: 150
  iface:
    - mantle
    - luwyi
    - jbnrz
    - daidr
    - syx
    - iraze
    - asakirain
    - elaina
    - ljcbaby
    - lay
    - gaga
```
